"""
ReportLab PDF proposal generator.

Produces a letter-size contractor proposal with:
  - Letterhead (contractor name, company, license, contact)
  - Proposal metadata (client, date, valid period, timeline)
  - Scope of work table (line items with qty, unit, costs, total)
  - Cost summary (materials / labor / permits / contingency / total)
  - Payment terms
  - Dual signature block (contractor + client)
  - "Generated by Groundwork" footer
"""
from __future__ import annotations

import io
import datetime
from typing import Any

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER

# ─── Brand palette ────────────────────────────────────────────────────────────
ORANGE    = colors.HexColor('#F97316')   # Groundwork primary
SLATE_900 = colors.HexColor('#0F172A')
SLATE_700 = colors.HexColor('#334155')
SLATE_500 = colors.HexColor('#64748B')
SLATE_300 = colors.HexColor('#CBD5E1')
SLATE_100 = colors.HexColor('#F1F5F9')
WHITE     = colors.white


def _style(name: str, **kwargs) -> ParagraphStyle:
    return ParagraphStyle(name=name, **kwargs)


# ─── Text styles ─────────────────────────────────────────────────────────────
_S = {
    'company':   _style('company',   fontSize=16, fontName='Helvetica-Bold',   textColor=SLATE_900),
    'meta':      _style('meta',      fontSize=9,  fontName='Helvetica',         textColor=SLATE_500),
    'label':     _style('label',     fontSize=8,  fontName='Helvetica-Bold',    textColor=SLATE_500,
                                     spaceAfter=2, letterSpacing=0.8),
    'value':     _style('value',     fontSize=11, fontName='Helvetica',         textColor=SLATE_900),
    'section':   _style('section',   fontSize=8,  fontName='Helvetica-Bold',    textColor=SLATE_500,
                                     letterSpacing=1.2, spaceBefore=4, spaceAfter=6),
    'body':      _style('body',      fontSize=11, fontName='Helvetica',         textColor=SLATE_700,
                                     leading=16),
    'total_lbl': _style('total_lbl', fontSize=12, fontName='Helvetica-Bold',    textColor=SLATE_900),
    'total_val': _style('total_val', fontSize=16, fontName='Helvetica-Bold',    textColor=ORANGE,
                                     alignment=TA_RIGHT),
    'footer':    _style('footer',    fontSize=8,  fontName='Helvetica',         textColor=SLATE_300,
                                     alignment=TA_CENTER),
    'sig_name':  _style('sig_name',  fontSize=10, fontName='Helvetica-Bold',    textColor=SLATE_700),
    'sig_role':  _style('sig_role',  fontSize=9,  fontName='Helvetica',         textColor=SLATE_500),
}


def _hr():
    return HRFlowable(width='100%', thickness=0.5, color=SLATE_300, spaceAfter=10, spaceBefore=6)


def _fmt(n: float | int) -> str:
    return f'${int(round(n)):,}'


# ─── PDF builder ─────────────────────────────────────────────────────────────

def build_proposal_pdf(
    estimate: dict[str, Any],
    contractor: dict[str, str],
    client: dict[str, str],
    payment_terms: str = '50% deposit due at signing, 50% on completion',
    valid_days: int = 30,
    proposal_id: str = '',
) -> bytes:
    """
    Build and return the proposal PDF as raw bytes.

    estimate   – the vision pipeline result dict (or a tier estimate dict)
    contractor – {name, company, license, phone, email}
    client     – {name, address, phone?, email?}
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    today = datetime.date.today().strftime('%B %-d, %Y')
    valid_until = (datetime.date.today() + datetime.timedelta(days=valid_days)).strftime('%B %-d, %Y')
    timeline_weeks = estimate.get('timeline_estimate_weeks') or estimate.get('timeline_weeks') or 4
    room_type = estimate.get('room_type', 'Renovation')
    room_label = room_type.replace('_', ' ').title()
    prop_num = (proposal_id[:8].upper() if proposal_id else
                datetime.datetime.now(datetime.timezone.utc).strftime('GW-%Y-%m%d'))

    line_items = (
        estimate.get('estimate_breakdown')
        or estimate.get('breakdown')
        or []
    )
    subtotal_materials = estimate.get('subtotal_materials', 0) or 0
    subtotal_labor     = estimate.get('subtotal_labor', 0) or 0
    permits            = estimate.get('permits', 0) or 0
    contingency        = estimate.get('contingency', 0) or 0
    total              = estimate.get('total_estimate', 0) or 0
    est_range          = estimate.get('estimate_range', {}) or {}
    scope_narrative    = estimate.get('scope_narrative', '') or ''

    story = []

    # ── Letterhead ─────────────────────────────────────────────────────────────
    letterhead_data = [[
        Paragraph(contractor.get('company', 'Contractor'), _S['company']),
        Paragraph(
            f"Lic. {contractor.get('license', '')} &nbsp; · &nbsp; "
            f"{contractor.get('phone', '')} &nbsp; · &nbsp; {contractor.get('email', '')}",
            _S['meta'],
        ),
    ]]
    lh_table = Table(letterhead_data, colWidths=['55%', '45%'])
    lh_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
    ]))
    story.append(lh_table)
    story.append(_hr())

    # ── Proposal header ────────────────────────────────────────────────────────
    header_data = [[
        Paragraph('<b>PROPOSAL</b>', _style('ph', fontSize=18, fontName='Helvetica-Bold',
                                            textColor=SLATE_900, letterSpacing=1.5)),
        Paragraph(f'#{prop_num}', _style('pid', fontSize=10, fontName='Helvetica',
                                          textColor=SLATE_500, alignment=TA_RIGHT)),
    ]]
    hdr_table = Table(header_data, colWidths=['70%', '30%'])
    hdr_table.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'MIDDLE')]))
    story.append(hdr_table)
    story.append(Spacer(1, 8))

    # Metadata grid (2-column)
    meta_pairs = [
        ('Project',      f'{room_label} Remodel'),
        ('Date',         today),
        ('Prepared for', client.get('name', '')),
        ('Address',      client.get('address', '')),
        ('Valid until',  valid_until),
        ('Timeline',     f'~{timeline_weeks} weeks'),
    ]
    meta_rows = []
    for i in range(0, len(meta_pairs), 2):
        left  = meta_pairs[i]
        right = meta_pairs[i + 1] if i + 1 < len(meta_pairs) else ('', '')
        meta_rows.append([
            Paragraph(left[0].upper(), _S['label']),
            Paragraph(right[0].upper(), _S['label']),
        ])
        meta_rows.append([
            Paragraph(left[1], _S['value']),
            Paragraph(right[1], _S['value']),
        ])
    meta_table = Table(meta_rows, colWidths=['50%', '50%'])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    story.append(meta_table)

    if scope_narrative:
        story.append(Spacer(1, 8))
        story.append(Paragraph(scope_narrative, _S['body']))

    story.append(_hr())

    # ── Scope of work table ────────────────────────────────────────────────────
    story.append(Paragraph('SCOPE OF WORK', _S['section']))

    col_widths = ['30%', '8%', '10%', '14%', '14%', '14%', '10%']
    w = doc.width
    cw = [w * float(p.strip('%')) / 100 for p in col_widths]

    tbl_data = [[
        Paragraph('<b>Description</b>',     _style('th', fontSize=9, fontName='Helvetica-Bold', textColor=SLATE_500)),
        Paragraph('<b>Qty</b>',             _style('th', fontSize=9, fontName='Helvetica-Bold', textColor=SLATE_500, alignment=TA_RIGHT)),
        Paragraph('<b>Unit</b>',            _style('th', fontSize=9, fontName='Helvetica-Bold', textColor=SLATE_500)),
        Paragraph('<b>Mat. / unit</b>',     _style('th', fontSize=9, fontName='Helvetica-Bold', textColor=SLATE_500, alignment=TA_RIGHT)),
        Paragraph('<b>Labor / unit</b>',    _style('th', fontSize=9, fontName='Helvetica-Bold', textColor=SLATE_500, alignment=TA_RIGHT)),
        Paragraph('<b>Line total</b>',      _style('th', fontSize=9, fontName='Helvetica-Bold', textColor=SLATE_500, alignment=TA_RIGHT)),
        Paragraph('<b>Source</b>',          _style('th', fontSize=9, fontName='Helvetica-Bold', textColor=SLATE_500)),
    ]]

    def _p(text: str, align=TA_LEFT, size=10, bold=False) -> Paragraph:
        fn = 'Helvetica-Bold' if bold else 'Helvetica'
        return Paragraph(str(text), _style('td', fontSize=size, fontName=fn,
                                            textColor=SLATE_700, alignment=align))

    for item in line_items:
        label       = item.get('item', '') or ''
        scope_desc  = item.get('scope', '') or ''
        desc        = f'{label}<br/><font size="8" color="#64748B">{scope_desc}</font>' if scope_desc else label
        qty_raw     = item.get('qty', 0) or 0
        qty_str     = f'{qty_raw:.1f}'.rstrip('0').rstrip('.') if isinstance(qty_raw, float) else str(qty_raw)
        unit        = (item.get('unit', '') or '').replace('_', ' ')
        mat         = _fmt(item.get('material_unit_cost', 0) or 0)
        lab         = _fmt(item.get('labor_unit_cost', 0) or 0)
        total_item  = _fmt(item.get('total', 0) or 0)
        source      = (item.get('source', 'vision') or 'vision').replace('claude_analysis', 'vision')
        tbl_data.append([
            Paragraph(desc, _style('tdc', fontSize=10, fontName='Helvetica', textColor=SLATE_700)),
            _p(qty_str, TA_RIGHT),
            _p(unit),
            _p(mat, TA_RIGHT),
            _p(lab, TA_RIGHT),
            _p(total_item, TA_RIGHT, bold=True),
            _p(source, size=9),
        ])

    scope_table = Table(tbl_data, colWidths=cw, repeatRows=1)
    scope_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), SLATE_100),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, SLATE_100]),
        ('GRID', (0, 0), (-1, -1), 0.25, SLATE_300),
        ('TOPPADDING',    (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING',   (0, 0), (-1, -1), 5),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(scope_table)
    story.append(_hr())

    # ── Cost summary ───────────────────────────────────────────────────────────
    story.append(Paragraph('COST SUMMARY', _S['section']))

    summary_rows = [
        ('Materials',       subtotal_materials),
        ('Labor',           subtotal_labor),
        ('Permits & fees',  permits),
        ('Contingency',     contingency),
    ]
    sum_data = [
        [Paragraph(lbl, _style('sl', fontSize=11, fontName='Helvetica', textColor=SLATE_700)),
         Paragraph(_fmt(val), _style('sv', fontSize=11, fontName='Helvetica',
                                     textColor=SLATE_700, alignment=TA_RIGHT))]
        for lbl, val in summary_rows
    ]
    sum_table = Table(sum_data, colWidths=['70%', '30%'])
    sum_table.setStyle(TableStyle([
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(sum_table)

    # Total row
    total_data = [[
        Paragraph('<b>TOTAL ESTIMATE</b>', _S['total_lbl']),
        Paragraph(f'<b>{_fmt(total)}</b>', _S['total_val']),
    ]]
    total_table = Table(total_data, colWidths=['70%', '30%'])
    total_table.setStyle(TableStyle([
        ('LINEABOVE', (0, 0), (-1, 0), 1, SLATE_300),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(total_table)

    if est_range.get('low') and est_range.get('high'):
        story.append(Paragraph(
            f'Estimated range: {_fmt(est_range["low"])} – {_fmt(est_range["high"])}',
            _style('range', fontSize=9, fontName='Helvetica', textColor=SLATE_500),
        ))

    story.append(_hr())

    # ── Payment terms ──────────────────────────────────────────────────────────
    story.append(Paragraph('PAYMENT TERMS', _S['section']))
    story.append(Paragraph(payment_terms, _S['body']))
    story.append(_hr())

    # ── Signature block ────────────────────────────────────────────────────────
    sig_data = [[
        [HRFlowable(width='90%', thickness=0.5, color=SLATE_300, spaceAfter=4),
         Paragraph(contractor.get('name', 'Contractor'), _S['sig_name']),
         Paragraph('Contractor', _S['sig_role'])],
        [HRFlowable(width='90%', thickness=0.5, color=SLATE_300, spaceAfter=4),
         Paragraph(client.get('name', 'Client'), _S['sig_name']),
         Paragraph('Client', _S['sig_role'])],
    ]]
    sig_table = Table(sig_data, colWidths=['50%', '50%'])
    sig_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(Spacer(1, 12))
    story.append(sig_table)

    # ── Footer ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 16))
    story.append(Paragraph('Generated by Groundwork · Camera-to-Estimate™', _S['footer']))

    doc.build(story)
    return buf.getvalue()
